name = "adauuid"
description = "Thin binding to libuuid"
version = "0.1.0"
authors = ["Pavel Zhukov"]
maintainers = ["Pavel Zhukov <pavel@zhukoff.net>"]
licenses = "GPL-3.0-or-later"
website = "https://github.com/landgraf/adauuid"

project-files = ["adauuid.gpr"]

[[depends-on]]
uuid = "*"

[gpr-externals]

[configuration]
disabled = false
